# Generated by Django 4.0.5 on 2022-06-15 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('draw', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='updatelog',
            name='log_text',
            field=models.TextField(max_length=1000),
        ),
    ]
