# Generated by Django 4.0.5 on 2022-06-16 04:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('draw', '0003_alter_updatelog_log_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='likes',
            field=models.PositiveIntegerField(default=0, editable=False, verbose_name='喜欢'),
        ),
        migrations.CreateModel(
            name='LikeNum',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('liked_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Liked_id', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Like_id', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'user',
            },
        ),
    ]
